# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CaraLivro' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Cloudinary'
  pod 'StringStylizer'
  # Pods for CaraLivro

  target 'CaraLivroTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CaraLivroUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
